name: hermes_mobile_control_plane
description: Native mobile shell for Hermes Mobile Control Plane.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  crypto: ^3.0.7
  cryptography: ^2.9.0
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
