import '../models/alpha_models.dart';
import 'alpha_repository.dart';

class MockAlphaRepository implements AlphaRepository {
  const MockAlphaRepository();

  @override
  Future<HomeAlphaSnapshot> loadHome() async {
    final agents = await loadAgents();
    final missions = await loadMissions();
    final inbox = await loadInbox();
    return HomeAlphaSnapshot(
      stats: const [
        DashboardStat(
            label: 'Agents', value: '12', trend: '9 online', intent: 'neutral'),
        DashboardStat(
            label: 'Online',
            value: '9',
            trend: '+2 since 09:00',
            intent: 'good'),
        DashboardStat(
            label: 'Missions',
            value: '4',
            trend: '2 running',
            intent: 'active'),
        DashboardStat(
            label: 'Approvals',
            value: '3',
            trend: '1 critical',
            intent: 'warn'),
        DashboardStat(
            label: 'Notifications',
            value: '18',
            trend: '5 unread',
            intent: 'active'),
        DashboardStat(
            label: 'Security',
            value: '1',
            trend: 'requires review',
            intent: 'critical'),
      ],
      pendingApprovals: _approvals,
      activeMissions: missions
          .where((mission) => mission.state != MissionState.complete)
          .toList(),
      agents: agents,
      activity: _activity,
      notifications:
          inbox.where((item) => item.kind != InboxKind.approval).toList(),
    );
  }

  @override
  Future<List<FleetAgent>> loadAgents() async => _agents;

  @override
  Future<FleetAgent> loadAgent(String agentId) async {
    return _agents.firstWhere((agent) => agent.id == agentId,
        orElse: () => _agents.first);
  }

  @override
  Future<List<MissionSummary>> loadMissions() async => _missions;

  @override
  Future<List<InboxItem>> loadInbox() async => _inbox;

  @override
  Future<ApprovalAlpha> loadApproval(String approvalId) async {
    return _approvals.firstWhere(
      (approval) => approval.id == approvalId,
      orElse: () => _approvals.first,
    );
  }

  @override
  Future<ApprovalAlpha> approveOnce(String approvalId) async {
    final approval = await loadApproval(approvalId);
    return approval.copyWith(state: 'approved');
  }

  @override
  Future<ApprovalAlpha> deny(String approvalId) async {
    final approval = await loadApproval(approvalId);
    return approval.copyWith(state: 'denied');
  }

  @override
  Future<AssistanceSessionAlpha> loadAssistanceSession(String sessionId) async {
    return AssistanceSessionAlpha(
      id: sessionId,
      agentName: 'Repo Sentinel',
      node: 'work-vm-02',
      mission: 'Release branch verification',
      state: AssistanceState.active,
      reason:
          'Agent needs operator guidance before rewriting generated migration files.',
      messages: const [
        AssistanceMessageAlpha(
          sender: 'Repo Sentinel',
          body:
              'I found migration files generated by two different tool versions.',
          timeLabel: '12:41',
          fromUser: false,
        ),
        AssistanceMessageAlpha(
          sender: 'You',
          body:
              'Compare the schema diff first. Do not write until I approve the exact file list.',
          timeLabel: '12:42',
          fromUser: true,
        ),
        AssistanceMessageAlpha(
          sender: 'Repo Sentinel',
          body:
              'Confirmed. I will inspect only and report back with affected paths.',
          timeLabel: '12:42',
          fromUser: false,
        ),
      ],
    );
  }

  @override
  Future<TerminalSessionAlpha> loadTerminalSession(String sessionId) async {
    return TerminalSessionAlpha(
      id: sessionId,
      agentName: 'Repo Sentinel',
      node: 'work-vm-02',
      mission: 'Release branch verification',
      prompt: 'hermes@work-vm-02 ~/repo %',
      scrollback: const [
        r'$ git status --short',
        ' M gateway/src/hermes_gateway/app.py',
        ' M docs/api/openapi.yaml',
        r'$ git diff --stat',
        ' gateway/src/hermes_gateway/app.py | 42 ++++++++++++++++++++++',
        ' docs/api/openapi.yaml             | 31 +++++++++++++++',
        r'$ uv run --project gateway pytest gateway/tests',
        '39 passed, 1 warning in 1.92s',
        r'$ git log --oneline -3',
        '39fac88 docs: specify TUI TUA and advanced approvals',
        '184d18c feat: add Hermes tool adapter and mobile data layer',
        '235e6e8 feat: add signed device requests and approval lifecycle',
      ],
    );
  }
}

const _agents = [
  FleetAgent(
    id: 'agent-repo',
    name: 'Repo Sentinel',
    team: 'Workstation',
    status: AgentRunStatus.running,
    node: 'work-vm-02',
    currentMission: 'Release branch verification',
    lastActivity: 'diff review 2m ago',
    capabilities: ['shell', 'git', 'files', 'tests'],
    notificationCount: 3,
    approvalCount: 1,
  ),
  FleetAgent(
    id: 'agent-home',
    name: 'Homelab Watch',
    team: 'Homelab',
    status: AgentRunStatus.online,
    node: 'nas-node',
    currentMission: 'Nightly backup audit',
    lastActivity: 'health event 6m ago',
    capabilities: ['logs', 'files', 'notify'],
    notificationCount: 2,
    approvalCount: 0,
  ),
  FleetAgent(
    id: 'agent-browser',
    name: 'Browser Bridge',
    team: 'Research',
    status: AgentRunStatus.blocked,
    node: 'laptop',
    currentMission: 'Vendor docs check',
    lastActivity: 'blocked 11m ago',
    capabilities: ['browser', 'screenshots', 'forms'],
    notificationCount: 5,
    approvalCount: 2,
  ),
  FleetAgent(
    id: 'agent-sec',
    name: 'PromptFence Guard',
    team: 'Security',
    status: AgentRunStatus.warning,
    node: 'vps-prod',
    currentMission: 'Tailnet access review',
    lastActivity: 'alert 14m ago',
    capabilities: ['audit', 'network', 'policy'],
    notificationCount: 4,
    approvalCount: 0,
  ),
  FleetAgent(
    id: 'agent-voice',
    name: 'Voice Scout',
    team: 'Research',
    status: AgentRunStatus.idle,
    node: 'studio-mac',
    currentMission: 'Waiting for callback',
    lastActivity: 'idle 27m ago',
    capabilities: ['voice', 'notify'],
    notificationCount: 1,
    approvalCount: 0,
  ),
];

const _missions = [
  MissionSummary(
    id: 'mission-release',
    title: 'Release branch verification',
    agentName: 'Repo Sentinel',
    team: 'Workstation',
    state: MissionState.running,
    progressLabel: 'Tests passed, diff review pending',
    lastEvent: 'Gateway tests completed successfully.',
  ),
  MissionSummary(
    id: 'mission-docs',
    title: 'Vendor docs check',
    agentName: 'Browser Bridge',
    team: 'Research',
    state: MissionState.blocked,
    progressLabel: 'Needs browser submit approval',
    lastEvent: 'Form submit blocked pending approval.',
  ),
  MissionSummary(
    id: 'mission-backup',
    title: 'Nightly backup audit',
    agentName: 'Homelab Watch',
    team: 'Homelab',
    state: MissionState.waiting,
    progressLabel: 'Awaiting NAS scrub result',
    lastEvent: 'ZFS scrub reached 82 percent.',
  ),
  MissionSummary(
    id: 'mission-tailnet',
    title: 'Tailnet access review',
    agentName: 'PromptFence Guard',
    team: 'Security',
    state: MissionState.running,
    progressLabel: 'Reviewing new device posture',
    lastEvent: 'Unknown workstation requested route advertisement.',
  ),
];

const _approvals = [
  ApprovalAlpha(
    id: 'appr-shell',
    title: 'Run migration cleanup command',
    agentName: 'Repo Sentinel',
    node: 'work-vm-02',
    session: 'release-branch-verification',
    risk: 'high',
    state: 'pending',
    requestedTool: 'shell',
    summary:
        'Agent wants to rewrite generated migration files before test rerun.',
    payloadPreview: 'command: python manage.py makemigrations --merge',
    expiresIn: '04:12',
    constraints: [
      'read-only first',
      'ask again before writing',
      'only this repo'
    ],
  ),
  ApprovalAlpha(
    id: 'appr-browser',
    title: 'Submit vendor docs feedback form',
    agentName: 'Browser Bridge',
    node: 'laptop',
    session: 'vendor-docs-check',
    risk: 'medium',
    state: 'pending',
    requestedTool: 'browser.submit',
    summary: 'Agent wants to submit a feedback form with a generated summary.',
    payloadPreview: 'target: docs.vendor.example/feedback',
    expiresIn: '08:45',
    constraints: ['show payload', 'no auth changes'],
  ),
  ApprovalAlpha(
    id: 'appr-network',
    title: 'Probe new tailnet route advertiser',
    agentName: 'PromptFence Guard',
    node: 'vps-prod',
    session: 'tailnet-access-review',
    risk: 'critical',
    state: 'pending',
    requestedTool: 'network.scan',
    summary: 'Security agent wants to inspect a newly advertised subnet route.',
    payloadPreview: 'scope: 100.92.14.0/24, read-only scan',
    expiresIn: '02:19',
    constraints: ['read-only first', 'ask again before writing'],
  ),
];

const _inbox = [
  InboxItem(
    id: 'appr-shell',
    kind: InboxKind.approval,
    title: 'Approval required',
    subtitle: 'Run migration cleanup command',
    agentName: 'Repo Sentinel',
    timeLabel: '2m',
    unread: true,
    priority: 'high',
  ),
  InboxItem(
    id: 'assist-release',
    kind: InboxKind.assistance,
    title: 'Agent needs help',
    subtitle: 'Generated migrations conflict with current schema.',
    agentName: 'Repo Sentinel',
    timeLabel: '4m',
    unread: true,
    priority: 'high',
  ),
  InboxItem(
    id: 'security-tailnet',
    kind: InboxKind.security,
    title: 'Security alert',
    subtitle: 'Unknown route advertiser detected on tailnet.',
    agentName: 'PromptFence Guard',
    timeLabel: '14m',
    unread: true,
    priority: 'critical',
  ),
  InboxItem(
    id: 'notify-backup',
    kind: InboxKind.notification,
    title: 'Backup audit update',
    subtitle: 'ZFS scrub reached 82 percent.',
    agentName: 'Homelab Watch',
    timeLabel: '18m',
    unread: false,
    priority: 'normal',
  ),
  InboxItem(
    id: 'appr-browser',
    kind: InboxKind.approval,
    title: 'Browser submit blocked',
    subtitle: 'Vendor feedback form needs review.',
    agentName: 'Browser Bridge',
    timeLabel: '22m',
    unread: false,
    priority: 'medium',
  ),
];

const _activity = [
  ActivityEvent(
    title: 'Tests passed',
    detail: 'Repo Sentinel completed gateway test suite.',
    timeLabel: '2m',
    severity: 'good',
  ),
  ActivityEvent(
    title: 'Approval opened',
    detail: 'Shell command pending operator review.',
    timeLabel: '3m',
    severity: 'warn',
  ),
  ActivityEvent(
    title: 'Security alert',
    detail: 'PromptFence Guard flagged a route advertisement.',
    timeLabel: '14m',
    severity: 'critical',
  ),
  ActivityEvent(
    title: 'Mission blocked',
    detail: 'Browser Bridge is waiting on form submit review.',
    timeLabel: '22m',
    severity: 'warn',
  ),
];
